version: 2
jobs:
  php_code_sniffer_and_unit_test:
    docker:
    - image: flickerleap/docker-circleci-laravel:latest
    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: composer install --no-interaction --ignore-platform-reqs --no-suggest --no-progress

    - save_cache:
        paths:
        - ./vendor
        key: v1-dependencies-{{ checksum "composer.json" }}

    - run:
        name: PHP - Code Sniff
        command:  ~/.composer/vendor/bin/phpcs --standard=PSR2 app/ -n

    - run:
        name: PHP - Unit Tests
        command: php ~/.composer/vendor/bin/phpunit --coverage-clover build/coverage/xml

    - run:
        name: Codacy - Code Coverage
        command: php  ~/.composer/vendor/bin/codacycoverage clover build/coverage/xml

workflows:
  version: 2
  build-all:
    jobs:
    - php_code_sniffer_and_unit_test
